theme: minima

baseurl: "/" # the subpath of your site, e.g. /blog
url: https://ppa4ipa.github.io # "http://artalph.com" # the base hostname & protocol for your site
permalink: /:title
email: soninas@gmail.com
author: Snejina Sonina
twitter_username: artalph
github_username:  ppa4ipa

title: PPA
longtitle: Pictographic Phonetic Alphabet

description: PPA is a system of phonetic signs that includes symbols functioning as didactic software and characters operating as a font.

header_pages:
  #- index.md
  - features.md
  - signs.md
  - apps.md
  - contacts.md
  
sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

plugins:
  - jekyll-sitemap
