remote_theme: aksakalli/jekyll-doc-theme@gh-pages #theme: minima
bootwatch: sandstone
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://ppa4ipa.com # the base hostname & protocol for your site
domain: ppa4ipa.com
#permalink: /:title
email: soninas@gmail.com
author: Snejina Sonina
twitter_username: ppa4ipa
github_username:  ppa4ipa

title: PPA
longtitle: Pictographic Phonetic Alphabet

description: PPA is a system of phonetic signs that includes symbols functioning as didactic software and characters operating as a font.

git_address: https://github.com/ArtAlph/artalph.github.io
git_edit_address: https://github.com/ArtAlph/artalph.github.ioo/blob/master

# header_pages:
#   #- index.md
#   - features.md
#   - signs.md
#   - apps.md
#   - contacts.md
  
sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]

defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "post"
  -
    scope:
      path: "signs"
    values:
      layout: null
      sitemap:
        exclude: "yes" # Exclude from sitemap.xml
  -
    scope:
      path: "signs/consonants"
    values:
      layout: consonant
  -
    scope:
      path: "signs/vowels"
    values:
      layout: vowel
  -
    scope:
      path: "signs/mods/figures"
    values:
      layout: mode_figure
  -
    scope:
      path: "signs/mods/signs"
    values:
      layout: mode_sign
  -
    scope:
      path: "signs/diacritics"
    values:
      layout: diacritic
  -
    scope:
      path: "404.html" # Exclude from sitemap.xml
    values:
      sitemap:
        exclude: "yes"
  -
    scope:
      path: "README.md" # Exclude from sitemap.xml
    values:
      sitemap:
        exclude: "yes"

plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
